# Generated by Django 3.0.6 on 2020-05-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=100)),
                ('Active_Cases', models.IntegerField()),
                ('Confirmed_Cases', models.IntegerField()),
                ('Recovered', models.IntegerField()),
                ('Deaths', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'states',
            },
        ),
    ]
