# Generated by Django 3.0.6 on 2020-05-21 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='states',
            name='Active_Cases',
        ),
        migrations.RemoveField(
            model_name='states',
            name='Confirmed_Cases',
        ),
        migrations.RemoveField(
            model_name='states',
            name='Deaths',
        ),
        migrations.RemoveField(
            model_name='states',
            name='Recovered',
        ),
    ]
