# Generated by Django 3.0.4 on 2020-06-18 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_auto_20200521_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='States',
        ),
    ]
